spring.application.name=employee-directory-api

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/employee_directory}
spring.datasource.username=${DB_USERNAME:springstudent}
spring.datasource.password=${DB_PASSWORD:springstudent}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=never
